### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by yyBeta** [henson/Answer#3]
```
panic: runtime error: index out of range

goroutine 5 [running]:
github.com/henson/Answer/api.Sogou(0xc04216c9e0, 0x4)
        E:/Projects/Go/src/github.com/henson/Answer/api/sogou.go:57 +0x71d
github.com/henson/Answer.answerQuestion.func1.1(0xc04203c480)
        E:/Projects/Go/src/github.com/henson/Answer/process.go:83 +0x3f
created by github.com/henson/Answer.answerQuestion.func1
        E:/Projects/Go/src/github.com/henson/Answer/process.go:82 +0x46
```

最新master分支，冲顶大会报错，看样子是搜狗的原因，但西瓜好像没问题。希望能错误处理一下让搜狗API故障时不影响搜索的决策方式

**Comment by henson** [comment]
收到，会在下一版中修改，谢谢提交

**Comment by henson** [comment]
已更改，请测试，谢谢！
